Tienda-V6/Controllers/ArticuloController.cs
using LibreriaV5_1_Final.Comun;
using LibreriaV5_1_Final.Modelo;
using LibreriaV5_1_Final.Negocio;
using LibreriaV5_1_Final.Persistencia;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Tienda_V6.Controllers
{
    public class ArticuloController : Controller
    {
        private ControlAccesoDAO<Object> control = new ControlAccesoDAO<Object>();

        public ActionResult Consultar()
        {
            Object[] modelos = new Object[2];
            TArticulo filtro = new TArticulo();
            filtro.Borrado = "0";
            List<Object> articulos = control.BuscarConPaginacion(filtro, 1);
            modelos[0] = articulos;
            modelos[1] = control.ContarRegistros(filtro);
            return View(modelos);
        }

        public ActionResult ver(string art)
        {
            TArticulo filtro = new TArticulo();
            filtro.CodArticulo = art;
            TArticulo articulo = (TArticulo)control.Buscar(filtro)[0];
            return View("ver", articulo);
        }

        [HttpPost]
        public ActionResult buscarConPaginacion(int numeroPagina)
        {
            Object[] modelos = new Object[2];
            TArticulo filtro = new TArticulo();
            filtro.Borrado = "0";
            List<Object> articulos = control.BuscarConPaginacion(filtro, numeroPagina);
            modelos[0] = articulos;
            modelos[1] = control.ContarRegistros(filtro);
            return Json(modelos);
        }

        public ActionResult add()
        {
            return View(control.Buscar(new TTipo()));
        }

        [HttpPost]
        public ActionResult add(TArticulo articulo)
        {
            String mensaje;
            try
            {
                //Hacemos la operaciones necesarias para guardar el nuevo libro.
                articulo.Precio = articulo.Precio.Replace(".", ",");
                articulo.CodArticulo = UtilSQL.GenerarCodigo(articulo.GetType());
                List<Object> articulos = new List<Object>();
                articulos.Add(articulo);
                control.Insertar(articulos);
                mensaje = Mensajes.MSG_INSERTADO_ARTICULO;
            }
            catch (Exception e)
            {
                mensaje = "ERR" + e.ToString();
            }
            return Json(mensaje);
        }

        public ActionResult modificar(string art)
        {
            TArticulo articulo = new TArticulo();
            articulo.CodArticulo = art;
            ViewBag.articulo = (TArticulo)control.Buscar(articulo)[0];
            return View(control.Buscar(new TTipo()));
        }

        [HttpPost]
        public ActionResult modificar(TArticulo articulo)
        {
            String mensaje;
            try
            {
                articulo.Precio = articulo.Precio.Replace(".", ",");
                List<Object> articulos = new List<Object>();
                articulos.Add(articulo);
                control.Modificar(articulos);
                mensaje = Mensajes.MSG_MODIFICADO_ARTICULO;
            }
            catch (Exception e)
            {
                mensaje = "ERR" + e.ToString();
            }
            return Json(mensaje);
        }

        [HttpPost]
        public PartialViewResult borrar(string art)
        {
            TArticulo filtro = new TArticulo();
            filtro.CodArticulo = art;
            control.BorradoVirtual(control.Buscar(filtro));
            filtro = new TArticulo();
            filtro.Borrado = "0";
            return PartialView("borrar", control.ContarRegistros(filtro));
        }

        public ActionResult compra()
        {
            List<TArticulo> list = new List<TArticulo>();
            foreach (var item in control.Buscar(new TArticulo()))
            {
                list.Add((TArticulo)item);
            }
            return View(list);
        }



        [HttpPost]
        public ActionResult obtener(string CodArticulo)
        {
            Object[] modelos = new Object[2];
            TArticulo filtro = new TArticulo()
            {
                CodArticulo = CodArticulo
            };
            filtro = (TArticulo)control.Buscar(filtro)[0];
            TLineaFactura linea = new TLineaFactura()
            {
                Articulo = CodArticulo,
                Cantidad = "1",
                Total = filtro.Precio
            };

            modelos[0] = filtro;
            modelos[1] = linea;
            // modelos[2] = control.ContarRegistros(filtro);
            return Json(modelos);
        }
    }
}

Tienda-V6/Views/Articulo/Consultar.cshtml
@using LibreriaV5_1_Final.Modelo
@{
    List<Object> articulos = Model[0];
    int registros = (Model[1] / 10) + 1;
}

<div id="form-main">
    <span id="totalArticulos" class="display-4">Total de articulos: @Model[1]</span>

    @if (((TUsuario)Session["usuario"]) != null && ((TUsuario)Session["usuario"]).Rol.Equals("Administrador"))
    {
        <ul id="myList">
            <table id="tabla" class="table">
                <tr>
                    <th scope="col">Articulo</th>
                    <th scope="col">Borrar</th>
                    <th scope="col">Ver</th>
                    <th scope="col">Modificar</th>
                </tr>
                @foreach (TArticulo articulo in articulos)
                {
                    <tr id="@articulo.CodArticulo" class="articulos">
                        <td>
                            @articulo.Nombre
                        </td>
                        <td>
                            @Ajax.ActionLink("Borrar", "borrar", "Articulo", new { art = articulo.CodArticulo }, new AjaxOptions()
                       {
                           HttpMethod = "POST",
                           InsertionMode = InsertionMode.Replace,
                           UpdateTargetId = "totalArticulos",
                       },new { onclick = "borrarArticulo(\"" + articulo.CodArticulo + "\")" ,  @class = "btn btn-danger" } )
                        </td>

                        <td scope="col"> @Html.ActionLink("Ver", "ver", "Articulo", new { art = articulo.CodArticulo }, new { @class = "btn btn-success" })</td>
                        <td> @Html.ActionLink("Editar", "modificar", "Articulo", new { art = articulo.CodArticulo }, new { @class = "btn btn-warning" })</td>

                    </tr>
                }

            </table>
        </ul>
        <br />
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                @for (int i = 0; i < registros; i++)
                {
                    int pagina = i + 1;
                    <li class="page-item"><a class="page-link paginacion" id="@pagina">@pagina</a></li>
                }

            </ul>
        </nav>

    }
    else if (((TUsuario)Session["usuario"]) != null && ((TUsuario)Session["usuario"]).Rol.Equals("Cliente"))
    {
        foreach (TArticulo articulo in articulos)
        {
            <li id="@articulo.CodArticulo">
                @articulo.Nombre
                @Html.ActionLink("Ver", "ver", "Articulo", new { art = articulo.CodArticulo }, null)
            </li>
        }

    }
</div>
<script src="https://code.jquery.com/jquery-3.2.1.js"></script>
@Scripts.Render("~/bundles/ArticulosConsulta")

Tienda-V6/Views/Articulo/borrar.cshtml
Total de articulos: @Model

Tienda-V6/Views/Articulo/modificar.cshtml
@using LibreriaV5_1_Final.Modelo
@{
    TArticulo articulo = ViewBag.articulo;
    List<Object> tipos = Model;
}
<h3 style="margin-bottom: 25px; text-align: center;">Editar artículo</h3>
<div class="container">
    <div id="mensaje" role="alert"></div>
    <div class="col-md-10">
        <div class="form-area">
            <form class="form" method="post" action="javascript:Enviar()">
                <input id="codArticulo" name="CodArticulo" type="hidden" value="@articulo.CodArticulo" />
                <div class="form-group">
                    <label for="nombre">Nombre</label>
                    <input name="Nombre" type="text" maxlength="30" required="" class="form-control" placeholder="Nombre" id="nombre" value="@articulo.Nombre" />
                </div>
                <div class="form-group">
                    <label for="fabricante">Fabricante</label>
                    <input name="Fabricante" type="text" maxlength="30" minlength="5" required="" class="form-control" placeholder="Fabricante" id="fabricante" value="@articulo.Fabricante" />
                </div>
                <div class="form-group">
                    <label for="tipo">Tipo</label>
                    <select name="Tipo" class="form-control" id="tipo">
                        @foreach (TTipo tipo in tipos)
                        {
                            if (tipo.Tipo.Equals(articulo.Tipo))
                            {
                                <option selected="selected" value="@tipo.Tipo">@tipo.Tipo</option>
                            }
                            else
                            {
                                <option value="@tipo.Tipo">@tipo.Tipo</option>
                            }

                        }
                    </select>
                </div>
                <div class="form-group">
                    <label for="precio">Precio</label>
                    <input name="Precio" type="text" required="" class="form-control" placeholder="Precio" id="precio" value="@articulo.Precio" />
                </div>
                <fieldset class="form-group">
                    <legend>Estado: </legend>
                    <input id="nuevo" type="radio" name="Estado" value="nuevo" @(articulo.Estado == "nuevo" ? "checked" : "") />Nuevo<br />
                    <input id="seminuevo" type="radio" name="Estado" value="seminuevo" @(articulo.Estado == "seminuevo" ? "checked" : "") />Seminuevo<br />
                    <input id="terceraMano" type="radio" name="Estado" value="tercera mano" @(articulo.Estado == "tercera mano" ? "checked" : "") />Tercera mano<br />
                </fieldset>
                <br>
                <div class="submit">
                    <!--Boton enviar, al pulsar HTTP se encarga de mandar los datos al servidor, en este caso es un metodo POST(Declarado en la etiqueta form al principio).
                        Se recomienda usar el metodo POST al enviar datos al servidor ya que van mas ocultos. Si usaramos GET, se veria toda la informacion en la barra de
                        direcciones. GET SIEMPRE PARA PEDIR DATOS AL SERVIDOR. POST SIEMPRE PARA ENVIAR DATOS AL SERVIDOR.
                        -->
                    <input type="submit" value="Modificar" class="btn btn-primary pull-right" id="button-blue" />
                    <div class="ease"></div>
                </div>
                <br>
                <div class="submit">
                    <input type="reset" value="Borrar Campos" class="btn btn-danger pull-right" id="button-reset">
                    <div class="ease"></div>
                </div>
            </form>
        </div>
    </div>
</div>
@Scripts.Render("~/bundles/ArticulosModificar")

Tienda-V6/Views/Articulo/ver.cshtml
@using LibreriaV5_1_Final.Modelo

@{ 
    TArticulo articulo = Model;
}
<h1 class="display-4">Datos del artículos</h1>
<table class="table">
    <tr>
        <td class="col-lg-6">Fabricante </td>
        <td class="col-lg-6">@articulo.Fabricante</td>
    </tr>
    <tr>
        <td class="col-lg-6">Nombre </td>
        <td class="col-lg-6">@articulo.Nombre</td>
    </tr>
    <tr>
        <td class="col-lg-6">Tipo </td>
        <td class="col-lg-6">@articulo.Tipo</td>
    </tr>
    <tr>
        <td class="col-lg-6">Precio </td>
        <td class="col-lg-6">@articulo.Precio</td>
    </tr>
    <tr>
        <td class="col-lg-6">Estado </td>
        <td class="col-lg-6">@articulo.Estado</td>
    </tr>
</table>