Tienda-V6/Controllers/PedidoController.cs
using LibreriaV5_1_Final.Comun;
using LibreriaV5_1_Final.Modelo;
using LibreriaV5_1_Final.Negocio;
using LibreriaV5_1_Final.Persistencia;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Tienda_V6.Controllers
{
    public class PedidoController : Controller
    {
        private ControlAccesoDAO<Object> control = new ControlAccesoDAO<Object>();

        public ActionResult consultar()
        {
            Object[] modelos = new Object[2];
            TFactura filtro = new TFactura();
            if (!((TUsuario)Session["usuario"]).Rol.Equals("Administrador"))
            {
                TCliente cliente = new TCliente()
                {
                    CodUsuario = ((TUsuario)Session["usuario"]).CodUsuario
                };
                cliente = (TCliente)control.Buscar(cliente)[0];
                filtro.Cliente = cliente.CodCliente;
            }
            filtro.Borrado = "0";
            List<Object> facturas = control.Buscar(filtro);
            modelos[0] = facturas;
            modelos[1] = control.ContarRegistros(filtro);
            return View(modelos);
        }

        [HttpPost]
        public ActionResult consultarConPaginacion(int numeroPagina)
        {
            Object[] modelos = new Object[2];
            TFactura filtro = new TFactura();
            if (!((TUsuario)Session["usuario"]).Rol.Equals("Administrador"))
            {
                TCliente cliente = new TCliente()
                {
                    CodUsuario = ((TUsuario)Session["usuario"]).CodUsuario
                };
                cliente = (TCliente)control.Buscar(cliente)[0];
                filtro.Cliente = cliente.CodCliente;
            }
            filtro.Borrado = "0";
            List<Object> facturas = control.BuscarConPaginacion(filtro,numeroPagina);
            modelos[0] = facturas;
            modelos[1] = control.ContarRegistros(filtro);
            return Json(modelos);
        }

        [HttpPost]
        public ActionResult ver(string fac)
        {
            List<Object> tLineasFacturas = null;
            if (isLegal(fac))
            {
                TLineaFactura filtro = new TLineaFactura();
                filtro.CodFactura = fac;
                tLineasFacturas = control.Buscar(filtro);
            }
            return Json(tLineasFacturas);
        }

        private bool isLegal(string fac)
        {
            bool legal = false;

            if (fac != null)
            {
                if (((TUsuario)Session["usuario"]).Rol.Equals("Cliente"))
                {
                    TCliente cliente = new TCliente()
                    {
                        CodUsuario = ((TUsuario)Session["usuario"]).CodUsuario
                    };
                    cliente = (TCliente)control.Buscar(cliente)[0];
                    TFactura filtro = new TFactura();
                    filtro.CodFactura = fac;
                    TFactura factura = (TFactura)control.Buscar(filtro)[0];
                    if (factura.Cliente.Equals(cliente.CodCliente))
                    {
                        legal = true;
                    }
                    else
                    {
                        legal = false;
                    }
                }
                else if (((TUsuario)Session["usuario"]).Rol.Equals("Administrador"))
                {
                    legal = true;
                }
            }
            return legal;
        }

        public ActionResult add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult add(TFactura factura, List<TLineaFactura> lineaFacturas)
        {
            String mensaje;
            try
            {
                factura.CodFactura = UtilSQL.GenerarCodigo(factura.GetType());
                List<Object> facturas = new List<Object>();
                facturas.Add(factura);
                control.Insertar(facturas);
                mensaje = Mensajes.MSG_INSERTADO_CLIENTE;
            }
            catch (Exception e)
            {
                mensaje = "ERR" + e.ToString();
            }
            return Json(mensaje);
        }

        public PartialViewResult borrar(string fac)
        {
            TFactura filtro = new TFactura();
            filtro.CodFactura = fac;
            control.BorradoVirtual(control.Buscar(filtro));
            filtro = new TFactura();
            filtro.Borrado = "0";
            return PartialView("borrar", control.Buscar(filtro).Count);
        }
    }
}

Tienda-V6/Views/Pedido/Consultar.cshtml
@using LibreriaV5_1_Final.Modelo
@{
    List<Object> pedidos = Model[0];
    int registros = (Model[1] / 10) + 1;
}

<div id="form-main">
    <span id="totalPedidos" class="display-4">Total de pedidos: @Model[1]</span>
    <ul id="myList">
        <table id="tabla" class="table">
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Fecha</th>
                <th scope="col">Ver</th>
            </tr>
            @foreach (TFactura pedido in pedidos)
            {
                <tr id="@pedido.CodFactura" class="clientes">
                    <td>
                        @pedido.CodFactura
                    </td>
                    <td>
                        @pedido.FechaFactura
                    </td>
                    <td>
                        @Ajax.ActionLink("Ver pedido", "ver", "Pedido", new { fac = pedido.CodFactura }, new AjaxOptions()
           {
               HttpMethod = "POST",
               OnSuccess = "exito",
               InsertionMode = InsertionMode.Replace,

           }, new { @class = "btn btn-success pop-up", data_toggle = "modal" ,data_target="#emergente"})
                    </td>
                </tr>
            }

        </table>
    </ul>
    <br />
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            @for (int i = 0; i < registros; i++)
            {
                int pagina = i + 1;
                <li class="page-item"><a class="page-link paginacion" id="@pagina">@pagina</a></li>
            }
        </ul>
    </nav>

</div>

<!-- Modal -->
<div class="modal fade" id="emergente" tabindex="-1" role="dialog" aria-labelledby="model">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="model">Pedido: </h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <br />
            </div>
            <div class="modal-body" id="container_lineas">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>

            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.js"></script>
@Scripts.Render("~/bundles/PedidosConsultar")

Tienda-V6/Views/Pedido/ver.cshtml
@using LibreriaV5_1_Final.Modelo

@{ 
    TCliente cliente = Model;
}
<h1 class="display-4">Datos del Cliente</h1>
<table class="table">
    <tr>
        <td class="col-lg-6">Apellidos </td>
        <td class="col-lg-6">@cliente.Apellidos</td>
    </tr>
    <tr>
        <td class="col-lg-6">Nombre </td>
        <td class="col-lg-6">@cliente.Nombre</td>
    </tr>
    <tr>
        <td class="col-lg-6">DNI </td>
        <td class="col-lg-6">@cliente.DNI</td>
    </tr>
    <tr>
        <td class="col-lg-6">Direccion </td>
        <td class="col-lg-6">@cliente.Direccion</td>
    </tr>
    <tr>
        <td class="col-lg-6">Correo electronico </td>
        <td class="col-lg-6">@cliente.Email</td>
    </tr>
</table>